authors:
  boegel:
    name: Kenneth Hoste
    description: HPC-UGent
    avatar: https://avatars.githubusercontent.com/u/620876?v=4
    slug: https://github.com/boegel
  laraPPr:
    name: Lara Peeters
    description: HPC-UGent
    avatar: https://avatars.githubusercontent.com/u/49882639?v=4
    slug: https://github.com/laraPPr
