authors:
  boegel:
    name: Kenneth Hoste
    description: HPC-UGent
    avatar: https://avatars.githubusercontent.com/u/620876?v=4
    slug: https://github.com/boegel
  casparvl:
    name: Caspar van Leeuwen
    description: SURF
    avatar: https://avatars.githubusercontent.com/u/33718780?v=4
    slug: https://github.com/casparvl
  jngrad:
    name: Jean-Noël Grad
    description: University of Stuttgart
    avatar: https://avatars.githubusercontent.com/u/42201407?v=4
    slug: https://github.com/jngrad
  laraPPr:
    name: Lara Peeters
    description: HPC-UGent
    avatar: https://avatars.githubusercontent.com/u/49882639?v=4
    slug: https://github.com/laraPPr
  satishskamath:
    name: Satish Kamath
    description: SURF
    avatar: https://avatars.githubusercontent.com/u/41335185?v=4
    slug: https://github.com/satishskamath
