# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: deploy documentation (only on push to main branch)
on:
  schedule: 
    # schedule the job to run at 12am every Saturday
    - cron: '0 0 * * 0'
  push:
    branches: main
# Declare default permissions as read only.
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      # Need to be able to write to the deploy branch
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # need to fetch all history to ensure correct Git revision dates in docs

    - name: set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: checkout test suite
      uses: actions/checkout@v4
      with:
        repository: eessi/test-suite
        
    - name: install mkdocs + plugins
      run: |
          pip install -r requirements.txt
          pip list | grep mkdocs
          mkdocs --version

    - name: build tutorial
      run: make test && make deploy
