# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Module overview script (lint + test)
on:
  push:
    paths:
      - 'scripts/**'
      - './.github/**'
  pull_request:
    paths:
      - 'scripts/**'
      - './.github/**'

# Declare default permissions as read only.
permissions: read-all
jobs:

  flake8-lint:
    runs-on: ubuntu-20.04
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: Set up Python environment
        uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # v4.3.0
        with:
          python-version: "3.6"
      - name: Run flake8
        uses: py-actions/flake8@84ec6726560b6d5bd68f2a5bed83d62b52bb50ba # v2.3.0
        with:
          max-line-length: "120"
          path: "scripts/available_software"

  pytest-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: Make EESSI available
        uses: eessi/github-action-eessi@v3
      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          cd scripts/available_software
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          cd scripts/available_software
          ./test.sh
